"""Exportable reports in various formats."""

import json
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any

from mnemosyne.analytics.summary import DailySummary, WeeklySummary
from mnemosyne.analytics.statistics import WorkStatistics


class ReportFormat(Enum):
    JSON = "json"
    MARKDOWN = "markdown"
    HTML = "html"


@dataclass
class ReportGenerator:
    output_dir: Path | None = None

    def __post_init__(self):
        if self.output_dir is None:
            self.output_dir = Path.home() / ".mnemosyne" / "reports"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_daily_report(
        self,
        summary: DailySummary,
        format: ReportFormat = ReportFormat.MARKDOWN,
    ) -> str:
        if format == ReportFormat.JSON:
            return self._daily_to_json(summary)
        elif format == ReportFormat.HTML:
            return self._daily_to_html(summary)
        else:
            return self._daily_to_markdown(summary)

    def generate_weekly_report(
        self,
        summary: WeeklySummary,
        format: ReportFormat = ReportFormat.MARKDOWN,
    ) -> str:
        if format == ReportFormat.JSON:
            return self._weekly_to_json(summary)
        elif format == ReportFormat.HTML:
            return self._weekly_to_html(summary)
        else:
            return self._weekly_to_markdown(summary)

    def save_report(
        self,
        content: str,
        name: str,
        format: ReportFormat,
    ) -> Path:
        ext = {
            ReportFormat.JSON: ".json",
            ReportFormat.MARKDOWN: ".md",
            ReportFormat.HTML: ".html",
        }[format]

        filename = f"{name}{ext}"
        filepath = self.output_dir / filename

        with open(filepath, "w") as f:
            f.write(content)

        return filepath

    def _daily_to_json(self, summary: DailySummary) -> str:
        data = {
            "date": summary.date.isoformat(),
            "headline": summary.headline,
            "productivity_score": summary.productivity_score,
            "total_hours": summary.total_hours,
            "top_apps": summary.top_apps,
            "highlights": summary.highlights,
            "insights": summary.insights,
            "recommendations": summary.recommendations,
        }
        return json.dumps(data, indent=2)

    def _daily_to_markdown(self, summary: DailySummary) -> str:
        lines = [
            f"# Daily Report - {summary.date.strftime('%Y-%m-%d')}",
            "",
            f"## {summary.headline}",
            "",
            "### Overview",
            f"- **Productivity Score**: {summary.productivity_score:.0f}/100",
            f"- **Total Active Time**: {summary.total_hours:.1f} hours",
            "",
        ]

        if summary.top_apps:
            lines.append("### Top Apps")
            for i, app in enumerate(summary.top_apps, 1):
                lines.append(f"{i}. {app}")
            lines.append("")

        if summary.highlights:
            lines.append("### Highlights")
            for highlight in summary.highlights:
                lines.append(f"- {highlight}")
            lines.append("")

        if summary.insights:
            lines.append("### Insights")
            for insight in summary.insights:
                lines.append(f"- {insight}")
            lines.append("")

        if summary.recommendations:
            lines.append("### Recommendations")
            for rec in summary.recommendations:
                lines.append(f"- {rec}")
            lines.append("")

        lines.append(f"---\n*Generated by Mnemosyne on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")

        return "\n".join(lines)

    def _daily_to_html(self, summary: DailySummary) -> str:
        score_color = self._get_score_color(summary.productivity_score)

        top_apps_html = "".join(f"<li>{app}</li>" for app in summary.top_apps)
        highlights_html = "".join(f"<li>{h}</li>" for h in summary.highlights)
        insights_html = "".join(f"<li>{i}</li>" for i in summary.insights)
        recommendations_html = "".join(f"<li>{r}</li>" for r in summary.recommendations)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Report - {summary.date.strftime('%Y-%m-%d')}</title>
    <style>
        :root {{ --score-color: {score_color}; }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0a0a0f; color: #e4e4e7; padding: 2rem; }}
        .container {{ max-width: 800px; margin: 0 auto; }}
        h1 {{ font-size: 2rem; margin-bottom: 0.5rem; background: linear-gradient(135deg, #8b5cf6, #ec4899); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }}
        h2 {{ font-size: 1.5rem; color: #a1a1aa; margin-bottom: 2rem; }}
        .score {{ display: inline-block; background: var(--score-color); color: white; padding: 0.5rem 1rem; border-radius: 0.5rem; font-size: 1.5rem; font-weight: bold; margin: 1rem 0; }}
        .stats {{ display: grid; grid-template-columns: repeat(2, 1fr); gap: 1rem; margin: 2rem 0; }}
        .stat {{ background: #12121a; padding: 1.5rem; border-radius: 0.75rem; border: 1px solid #27272a; }}
        .stat-label {{ color: #a1a1aa; font-size: 0.875rem; }}
        .stat-value {{ font-size: 1.5rem; font-weight: bold; margin-top: 0.25rem; }}
        section {{ background: #12121a; padding: 1.5rem; border-radius: 0.75rem; border: 1px solid #27272a; margin: 1rem 0; }}
        section h3 {{ color: #8b5cf6; margin-bottom: 1rem; }}
        ul {{ list-style: none; }}
        li {{ padding: 0.5rem 0; border-bottom: 1px solid #27272a; }}
        li:last-child {{ border-bottom: none; }}
        .footer {{ margin-top: 2rem; text-align: center; color: #a1a1aa; font-size: 0.875rem; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Daily Report</h1>
        <h2>{summary.date.strftime('%A, %B %d, %Y')}</h2>
        
        <p style="font-size: 1.25rem; margin-bottom: 1rem;">{summary.headline}</p>
        
        <div class="score">{summary.productivity_score:.0f}/100</div>
        
        <div class="stats">
            <div class="stat">
                <div class="stat-label">Active Time</div>
                <div class="stat-value">{summary.total_hours:.1f}h</div>
            </div>
            <div class="stat">
                <div class="stat-label">Top App</div>
                <div class="stat-value">{summary.top_apps[0] if summary.top_apps else 'N/A'}</div>
            </div>
        </div>
        
        {"<section><h3>Top Apps</h3><ul>" + top_apps_html + "</ul></section>" if summary.top_apps else ""}
        {"<section><h3>Highlights</h3><ul>" + highlights_html + "</ul></section>" if summary.highlights else ""}
        {"<section><h3>Insights</h3><ul>" + insights_html + "</ul></section>" if summary.insights else ""}
        {"<section><h3>Recommendations</h3><ul>" + recommendations_html + "</ul></section>" if summary.recommendations else ""}
        
        <div class="footer">Generated by Mnemosyne</div>
    </div>
</body>
</html>"""

    def _weekly_to_json(self, summary: WeeklySummary) -> str:
        data = {
            "start_date": summary.start_date.isoformat(),
            "end_date": summary.end_date.isoformat(),
            "headline": summary.headline,
            "average_productivity": summary.average_productivity,
            "total_hours": summary.total_hours,
            "most_used_apps": summary.most_used_apps,
            "weekly_insights": summary.weekly_insights,
            "trends": summary.trends,
            "recommendations": summary.recommendations,
            "daily_summaries": [
                {
                    "date": d.date.isoformat(),
                    "headline": d.headline,
                    "productivity_score": d.productivity_score,
                    "total_hours": d.total_hours,
                }
                for d in summary.daily_summaries
            ],
        }
        return json.dumps(data, indent=2)

    def _weekly_to_markdown(self, summary: WeeklySummary) -> str:
        lines = [
            f"# Weekly Report",
            f"## {summary.start_date.strftime('%b %d')} - {summary.end_date.strftime('%b %d, %Y')}",
            "",
            f"### {summary.headline}",
            "",
            "### Overview",
            f"- **Average Productivity**: {summary.average_productivity:.0f}/100",
            f"- **Total Active Time**: {summary.total_hours:.1f} hours",
            "",
            "### Daily Breakdown",
            "| Day | Hours | Productivity |",
            "|-----|-------|--------------|",
        ]

        for d in summary.daily_summaries:
            lines.append(f"| {d.date.strftime('%a %m/%d')} | {d.total_hours:.1f}h | {d.productivity_score:.0f}% |")

        lines.append("")

        if summary.most_used_apps:
            lines.append("### Most Used Apps")
            for i, app in enumerate(summary.most_used_apps[:5], 1):
                lines.append(f"{i}. {app}")
            lines.append("")

        if summary.weekly_insights:
            lines.append("### Insights")
            for insight in summary.weekly_insights:
                lines.append(f"- {insight}")
            lines.append("")

        if summary.recommendations:
            lines.append("### Recommendations for Next Week")
            for rec in summary.recommendations:
                lines.append(f"- {rec}")
            lines.append("")

        lines.append(f"---\n*Generated by Mnemosyne on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")

        return "\n".join(lines)

    def _weekly_to_html(self, summary: WeeklySummary) -> str:
        score_color = self._get_score_color(summary.average_productivity)

        daily_rows = "".join(
            f"<tr><td>{d.date.strftime('%a %m/%d')}</td><td>{d.total_hours:.1f}h</td><td>{d.productivity_score:.0f}%</td></tr>"
            for d in summary.daily_summaries
        )

        apps_html = "".join(f"<li>{app}</li>" for app in summary.most_used_apps[:5])
        insights_html = "".join(f"<li>{i}</li>" for i in summary.weekly_insights)
        recommendations_html = "".join(f"<li>{r}</li>" for r in summary.recommendations)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weekly Report - {summary.start_date.strftime('%b %d')} - {summary.end_date.strftime('%b %d')}</title>
    <style>
        :root {{ --score-color: {score_color}; }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0a0a0f; color: #e4e4e7; padding: 2rem; }}
        .container {{ max-width: 900px; margin: 0 auto; }}
        h1 {{ font-size: 2rem; margin-bottom: 0.5rem; background: linear-gradient(135deg, #8b5cf6, #ec4899); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }}
        h2 {{ font-size: 1.25rem; color: #a1a1aa; margin-bottom: 2rem; }}
        .headline {{ font-size: 1.25rem; margin-bottom: 1.5rem; }}
        .score {{ display: inline-block; background: var(--score-color); color: white; padding: 0.5rem 1rem; border-radius: 0.5rem; font-size: 1.5rem; font-weight: bold; margin: 1rem 0; }}
        .stats {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; margin: 2rem 0; }}
        .stat {{ background: #12121a; padding: 1.5rem; border-radius: 0.75rem; border: 1px solid #27272a; text-align: center; }}
        .stat-label {{ color: #a1a1aa; font-size: 0.875rem; }}
        .stat-value {{ font-size: 1.5rem; font-weight: bold; margin-top: 0.25rem; }}
        table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
        th, td {{ padding: 0.75rem; text-align: left; border-bottom: 1px solid #27272a; }}
        th {{ color: #a1a1aa; font-weight: normal; }}
        section {{ background: #12121a; padding: 1.5rem; border-radius: 0.75rem; border: 1px solid #27272a; margin: 1rem 0; }}
        section h3 {{ color: #8b5cf6; margin-bottom: 1rem; }}
        ul {{ list-style: none; }}
        li {{ padding: 0.5rem 0; border-bottom: 1px solid #27272a; }}
        li:last-child {{ border-bottom: none; }}
        .footer {{ margin-top: 2rem; text-align: center; color: #a1a1aa; font-size: 0.875rem; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Weekly Report</h1>
        <h2>{summary.start_date.strftime('%B %d')} - {summary.end_date.strftime('%B %d, %Y')}</h2>
        
        <p class="headline">{summary.headline}</p>
        
        <div class="stats">
            <div class="stat">
                <div class="stat-label">Avg Productivity</div>
                <div class="stat-value" style="color: var(--score-color);">{summary.average_productivity:.0f}%</div>
            </div>
            <div class="stat">
                <div class="stat-label">Total Hours</div>
                <div class="stat-value">{summary.total_hours:.1f}h</div>
            </div>
            <div class="stat">
                <div class="stat-label">Daily Average</div>
                <div class="stat-value">{summary.total_hours/7:.1f}h</div>
            </div>
        </div>
        
        <section>
            <h3>Daily Breakdown</h3>
            <table>
                <thead><tr><th>Day</th><th>Hours</th><th>Productivity</th></tr></thead>
                <tbody>{daily_rows}</tbody>
            </table>
        </section>
        
        {"<section><h3>Most Used Apps</h3><ul>" + apps_html + "</ul></section>" if summary.most_used_apps else ""}
        {"<section><h3>Insights</h3><ul>" + insights_html + "</ul></section>" if summary.weekly_insights else ""}
        {"<section><h3>Recommendations</h3><ul>" + recommendations_html + "</ul></section>" if summary.recommendations else ""}
        
        <div class="footer">Generated by Mnemosyne</div>
    </div>
</body>
</html>"""

    def _get_score_color(self, score: float) -> str:
        if score >= 70:
            return "#22c55e"
        elif score >= 40:
            return "#f59e0b"
        else:
            return "#ef4444"
