name: Bug Report
description: Report a bug in Mnemosyne
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have read the documentation
          required: true
        - label: I have run `mnemosyne doctor` and included the output below
          required: true
        
  - type: textarea
    id: doctor-output
    attributes:
      label: Doctor Output
      description: |
        **Required:** Run `mnemosyne doctor` and paste the full output below.
        This helps us diagnose your environment quickly.
      placeholder: |
        ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
        ┃ Check             ┃ Status ┃ Details                           ┃
        ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
        │ Mnemosyne version │ ✓      │ 0.1.0                             │
        ...
      render: shell
    validations:
      required: true
        
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
      placeholder: Tell us what you see!
    validations:
      required: true
       
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
       
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run 'mnemosyne ...'
        2. Click on '...'
        3. See error
    validations:
      required: true
       
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CLI
        - Web Interface
        - TUI
        - Recording (Capture)
        - LLM Integration
        - Memory System
        - Execution Agent
        - Plugin System
        - Other
    validations:
      required: true
       
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true
       
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell
